[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "atr-datasetcleaner"
version = "0.1.1"
description = "Dataset cleaning utilities"
requires-python = ">=3.8"

[tool.setuptools]
py-modules = ["cleaner"]
